use_frameworks!

platform :ios, '9.0'

target 'MyFramework_Example' do
  pod 'MyFramework', :path => '../'

  target 'MyFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
